// KLASA TESTOWA

//package pl.finalproject.accessingdatamysql.controller;
//
//import org.springframework.beans.factory.annotation.Autowired;
//import org.springframework.stereotype.Controller;
//import org.springframework.web.bind.annotation.GetMapping;
//import org.springframework.web.bind.annotation.PostMapping;
//import org.springframework.web.bind.annotation.RequestMapping;
//import org.springframework.web.bind.annotation.RequestParam;
//import org.springframework.web.bind.annotation.ResponseBody;
//import pl.finalproject.accessingdatamysql.model.User;
//import pl.finalproject.accessingdatamysql.repository.UserRepository;
//
//@Controller // This means that this class is a Controller
//@RequestMapping(path = "/main") // This means URL's start with /demo (after Application path)
//public class MainController {
//    @Autowired // This means to get the bean called userRepository
//    // Which is auto-generated by Spring, we will use it to handle the data
//    private UserRepository userRepository;
//
//    @GetMapping(path = "/add") // Map ONLY POST Requests
//    public String addNewUser(@RequestParam String email,
//                             @RequestParam String login) {
//        // @ResponseBody means the returned String is the response, not a view name
//        // @RequestParam means it is a parameter from the GET or POST request
//
//        User n = new User();
//        n.setEmail(email);
//        n.setLogin(login);
//        userRepository.save(n);
//        return "savedUserSuccess";
//    }
//
//    @GetMapping(path = "/all")
//    @ResponseBody
//    public Iterable<User> getAllUsers() {
//        // This returns a JSON or XML with the users
//        return userRepository.findAll();
//    }
//
//}
